---
title: "UMD Biostatistics: Schedule"
page-layout: full
---

This page contains the schedule and links for lectures, activities, homework, and vignettes for Ecostats Fall 2026. 
I am currently working on updating the lectures and intro specificall so we have more trianing for using r to facilitate doing the statistics easier.

::: {.column-screen-inset-right}

### Week 1: Foundations
::: {layout-ncol=2}
#### 01 - Introduction - Start with R
* [🖥️ Lecture](lectures/01_01_intro_start_with_r/intro_start_with_r.qmd)
* [📋 Activity](activities/01_01_intro_start_with_r_activity/intro_start_with_r_activity.qmd)
* [💻 Homework](homeworks/01_01_intro_r_homework/intro_r_homework.qmd)
* [📖 Vignette: T-Tests (Parametric)](vignettes/01_01_two_sample_ttest_vignette/two_sample_ttest.qmd)

#### 02 - Project Design and Graphing data
* [🖥️ Lecture](lectures/01_02_project_design_graphing/project_design_graphing.qmd)
* [📋 Activity](activities/01_02_project_design_graphing_activity/project_design_graphing_activity.qmd)
:::

---

### Week 2: Data & Probability
::: {layout-ncol=2}
#### 03 - Descriptive Stats and Wrangling
* [🖥️ Lecture](lectures/02_03_descriptive_stats_wrangling/descriptive_stats_wrangling.qmd)
* [📋 Activity](activities/02_03_descriptive_stats_wrangling_activity/descriptive_stats_wrangling_activity.qmd)
* [💻 Homework](homeworks/02_02_descriptive_stats_homework/descriptive_stats_homework.qmd)
* [📖 Vignette: T-Tests (Non-Parametric)](vignettes/02_02_welch_ttest_vignette/welch_ttest.qmd)

#### 04 - Probability and Inference I
* [🖥️ Lecture](lectures/02_04_probability_inference/probability_inference.qmd)
* [📋 Activity](activities/02_04_probability_inference_activity/probability_inference_activity.qmd)
:::

---

### Week 3: Mean Comparisons
::: {layout-ncol=2}
#### 05 - T-Tests - one - two - paired
* [🖥️ Lecture](lectures/03_05_t_tests/t_tests.qmd)
* [📋 Activity](activities/03_05_t_tests_activity/t_tests_activity.qmd)
* [💻 Homework](homeworks/03_03_t_test_homework/t_test_homework.qmd)
* [📖 Vignette: Correlation](vignettes/03_03_correlation_vignette/correlation.qmd)

#### 06 - Power and Type I and II error
* [🖥️ Lecture](lectures/03_06_power_and_error/power_and_error.qmd)
* [📋 Activity](activities/03_06_power_and_error_activity/power_and_error_activity.qmd)
:::

---

### Week 4: Experimental Design
::: {layout-ncol=2}
#### 07 - Non Parametric T-Tests
* [🖥️ Lecture](lectures/04_07_nonparametric_t_tests/nonparametric_t_tests.qmd)
* [📋 Activity](activities/04_07_nonparametric_t_tests_activity/nonparametric_t_tests_activity.qmd)
* [💻 Homework](homeworks/04_04_nonparametric_homework/nonparametric_homework.qmd)
* [📖 Vignette: Regression](vignettes/04_04_linear_regression_vignette/linear_regression.qmd)

#### 08 - Study Design and Sampling
* [🖥️ Lecture](lectures/04_08_study_design_sampling/study_design_sampling.qmd)
* [📋 Activity](activities/04_08_study_design_sampling_activity/study_design_sampling_activity.qmd)
:::

---

### Week 5: Relationship Modeling
::: {layout-ncol=1}
#### 09 - Correlation vs Linear Models
* [🖥️ Lecture](lectures/05_09_correlation_linear_models/correlation_linear_models.qmd)
* [📋 Activity](activities/05_09_correlation_linear_models_activity/correlation_linear_models_activity.qmd)
* [💻 Homework](homeworks/05_05_correlation_regression_homework/correlation_regression_homework.qmd)
* [📖 Vignette: Multiple Linear Regression](vignettes/05_05_multiple_linear_regression_vignette/multiple_linear_regression.qmd)
:::

---

### Week 6: Regression & ANOVA
::: {layout-ncol=2}
#### 10 - Multiple Regression
* [🖥️ Lecture](lectures/06_10_multiple_regression/multiple_regression.qmd)
* [📋 Activity](activities/06_10_multiple_regression_activity/multiple_regression_activity.qmd)
* [💻 Homework](homeworks/06_06_multiple_regression_homework/multiple_regression_homework.qmd)
* [📖 Vignette: One-way ANOVA](vignettes/06_06_one_way_anova_vignette/one_way_anova.qmd)

#### 11 - Analysis of Variance
* [🖥️ Lecture](lectures/06_11_analysis_of_variance/analysis_of_variance.qmd)
* [📋 Activity](activities/06_11_analysis_of_variance_activity/analysis_of_variance_activity.qmd)
* [💻 Homework](homeworks/06_07_one_way_anova_homework/one_way_anova_homework.qmd)
:::

---

### Week 7: Complex ANOVA & LMM
::: {layout-ncol=2}
#### 12 - 2 way ANOVA
* [🖥️ Lecture](lectures/07_12_two_way_anova/two_way_anova.qmd)
* [📋 Activity](activities/07_12_two_way_anova_activity/two_way_anova_activity.qmd)
* [💻 Homework](homeworks/07_08_factorial_anova_homework/factorial_anova_homework.qmd)
* 📖 Vignette: Two-factor ANOVA *(Coming Soon)*

#### 13 - Nested ANOVAs
* [🖥️ Lecture](lectures/07_13_nested_anova/nested_anova.qmd)
* [📋 Activity](activities/07_13_nested_anova_activity/nested_anova_activity.qmd)
* [💻 Homework](homeworks/07_09_lmm_homework/lmm_homework.qmd)
* 📖 Vignette: Linear Mixed Models *(Coming Soon)*
:::

---

### Week 8: GLMs
::: {layout-ncol=2}
#### 14 - GLM and Logistic Regression
* [🖥️ Lecture](lectures/08_14_glm_logistic_regression/glm_logistic_regression.qmd)
* [📋 Activity](activities/08_14_glm_logistic_regression_activity/glm_logistic_regression_activity.qmd)
* 📖 Vignette: PCA *(Coming Soon)*

#### 15 - ANCOVA - Analysis of Covariance
* [🖥️ Lecture](lectures/08_15_ancova/ancova.qmd)
* [📋 Activity](activities/08_15_ancova_activity/ancova_activity.qmd)
* [💻 Homework](homeworks/08_10_ancova_homework/ancova_homework.qmd)
:::

---

### Week 9: Multivariate Analysis
::: {layout-ncol=2}
#### 16 - Multivariate Statistics
* [🖥️ Lecture](lectures/09_16_multivariate_statistics/multivariate_statistics.qmd)
* [📋 Activity](activities/09_16_multivariate_statistics_activity/multivariate_statistics_activity.qmd)
* 📖 Vignette: NMDS *(Coming Soon)*

#### 17 - Principal Component Analysis
* [🖥️ Lecture](lectures/09_17_pca/pca.qmd)
* [📋 Activity](activities/09_17_pca_activity/pca_activity.qmd)
:::

---

### Week 10: Review & Finals
::: {layout-ncol=2}
#### 18 - NMDS - Cluster Analysis
* [🖥️ Lecture](lectures/10_18_nmds_cluster_analysis/nmds_cluster_analysis.qmd)
* [📋 Activity](activities/10_18_nmds_cluster_analysis_activity/nmds_cluster_analysis_activity.qmd)

#### 19 - Review
* [🖥️ Lecture](lectures/10_19_review/review.qmd)
:::

:::